name: Junit

on:
  pull_request:
    branches:
      - main
      - develop  # 例として、mainとdevelopブランチへのPRに対してトリガー

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      run: sudo apt-get install docker-compose

    - name: Build and start containers with docker-compose
      run: |
        docker-compose -f docker-compose.yml up -d  # バックグラウンドでコンテナを起動

    - name: Run tests inside the container
      run: |
        docker-compose exec -T app mvn test
    - name: Tear down Docker Compose
      run: docker-compose down  # テスト後にコンテナを停止
  